// Provider-agnostic giving-checkout contract — mirrors ISmsProvider's shape,
// not IPaymentProvider's: credentials are passed per call, never injected
// from ConfigService at construction, since every tenant brings their own
// Paystack/Flutterwave/Kora/Stripe account (BYOK), there is no platform
// merchant account behind this the way billing's IPaymentProvider has.
export type GivingProviderCredentials = Record<string, string>;

export interface GivingCheckoutParams {
  amountCents: number;
  currency: string;
  payerEmail: string;
  payerName: string;
  // GivingCheckoutSession.id — generated by GivingCheckoutService before
  // calling the provider, echoed back verbatim on the webhook so the
  // session can be looked up by it, never trusting anything else in the
  // webhook payload for identity/amount.
  reference: string;
  successUrl: string;
  cancelUrl: string;
  credentials: GivingProviderCredentials;
}

export interface GivingCheckoutResult {
  checkoutUrl: string;
}

export type GivingEventType = 'charge.succeeded' | 'charge.failed';

export interface NormalizedGivingEvent {
  type: GivingEventType;
  // The same reference GivingCheckoutService generated and handed to the
  // provider at checkout-initiation time, echoed back on the webhook —
  // looked up against GivingCheckoutSession.id, never read for
  // amount/member/tenant identity from the payload itself.
  providerReference?: string;
  raw: unknown;
}

export interface IGivingProvider {
  readonly providerName: string;

  createCheckoutSession(
    params: GivingCheckoutParams,
  ): Promise<GivingCheckoutResult>;

  verifyAndParseWebhook(
    rawBody: Buffer,
    signatureHeader: string,
    credentials: GivingProviderCredentials,
  ): NormalizedGivingEvent;
}

// Registry keys — also GivingProvider.id (catalog row), the stored
// GivingCheckoutSession.provider value, and TenantGivingProviderConfig's
// providerId.
export const PAYSTACK_GIVING_PROVIDER_NAME = 'paystack';
export const FLUTTERWAVE_GIVING_PROVIDER_NAME = 'flutterwave';
export const KORA_GIVING_PROVIDER_NAME = 'kora';
export const STRIPE_GIVING_PROVIDER_NAME = 'stripe';
