// Generated once from the pre-catalogue templates (Phase 3); edit freely, it isn't regenerated.
import { EmailCategory } from '../utility/email-provider/email-category.enum';
import type { EmailTemplate } from './email-catalogue';

type Data = Record<string, unknown>;

// Placeholder name -> template data key.
function pick(map: Record<string, string>) {
  return (d: Data): Record<string, string> =>
    Object.fromEntries(
      Object.entries(map).map(([name, dataKey]) => [
        name,
        d[dataKey] == null ? '' : String(d[dataKey]),
      ]),
    );
}

export const EXTRA_EMAIL_CATALOGUE: Record<string, EmailTemplate> = {
  'account-deactivated': {
    category: null,
    label: 'Account deactivated',
    description: "Sent when an admin deactivates a member's account.",
    lockedNote: 'Nothing is locked — the whole message is yours.',
    subject: '{{default_subject}}',
    heading: 'Account Deactivated, {{first_name}}',
    message:
      '<p>Your account has been deactivated. You will not be able to log in until your account is reactivated by an admin.</p><p>If you believe this is an error, please contact an admin directly.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your {{church_name}} account has been deactivated.',
    placeholders: { default_subject: 'Account deactivated', first_name: 'Ada' },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'account-reactivated': {
    category: null,
    label: 'Account reactivated',
    description: "Sent when an admin reactivates a member's account.",
    lockedNote: 'The sign-in button is always included.',
    subject: '{{default_subject}}',
    heading: 'Account Reactivated, {{first_name}}',
    message:
      '<p>Great news! Your account has been reactivated. You can now log in and access the app.</p>',
    closing:
      '<p>If you did not expect this, please contact an admin immediately.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your {{church_name}} account has been reactivated.',
    placeholders: { default_subject: 'Account reactivated', first_name: 'Ada' },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'asset-checkout-notification': {
    category: EmailCategory.ASSET_ALERTS,
    label: 'Asset checked out',
    description: 'Sent when church equipment is checked out to someone.',
    lockedNote: 'The asset details table is always included.',
    subject: '{{default_subject}}',
    heading: 'Asset Checked Out to You',
    message:
      '<p>Hi {{recipient_name}},</p><p>The following asset has been checked out to <strong>{{recipient_label}}</strong> by <strong>{{issued_by}}</strong>. Please handle it with care and ensure it is returned by the expected date.</p>',
    closing:
      '<p>If you have any questions, please contact your church administrator.</p>',
    signoff: '',
    signature: '',
    preheader:
      'Asset checked out to you: {{asset_name}} ({{tag_number}}) — please handle with care and return by {{expected_return_at}} .',
    placeholders: {
      default_subject: 'Asset checked out',
      asset_name: 'Projector',
      category: 'Audio/Visual',
      checked_out_at: '2026-09-20',
      expected_return_at: '2026-09-27',
      issued_by: 'Media Team',
      location: 'Main Auditorium',
      purpose: 'Youth programme',
      recipient_label: 'Checked out to',
      recipient_name: 'Tunde Bello',
      tag_number: 'AV-012',
    },
    toVars: pick({
      asset_name: 'assetName',
      category: 'category',
      checked_out_at: 'checkedOutAt',
      expected_return_at: 'expectedReturnAt',
      issued_by: 'issuedBy',
      location: 'location',
      purpose: 'purpose',
      recipient_label: 'recipientLabel',
      recipient_name: 'recipientName',
      tag_number: 'tagNumber',
    }),
    sampleData: {
      assetName: 'Projector',
      category: 'Audio/Visual',
      checkedOutAt: '2026-09-20',
      expectedReturnAt: '2026-09-27',
      issuedBy: 'Media Team',
      location: 'Main Auditorium',
      purpose: 'Youth programme',
      recipientLabel: 'Checked out to',
      recipientName: 'Tunde Bello',
      tagNumber: 'AV-012',
    },
  },
  'asset-maintenance-reminder': {
    category: EmailCategory.ASSET_ALERTS,
    label: 'Asset maintenance due',
    description:
      'Sent when church equipment is due or overdue for maintenance.',
    lockedNote: 'The maintenance details and button are always included.',
    subject: '{{default_subject}}',
    heading: '',
    message: '',
    closing: '',
    signoff: 'Regards,',
    signature: '{{church_name}} System',
    preheader: 'Maintenance for {{asset_name}} is due {{timing}}.',
    placeholders: {
      default_subject: 'Asset maintenance due',
      asset_name: 'Projector',
      category: 'Audio/Visual',
      location: 'Main Auditorium',
      next_due_at: '2026-10-14',
      tag_number: 'AV-012',
      timing: 'in 14 days',
    },
    toVars: pick({
      asset_name: 'assetName',
      category: 'category',
      location: 'location',
      next_due_at: 'nextDueAt',
      tag_number: 'tagNumber',
      timing: 'timing',
    }),
    sampleData: {
      assetName: 'Projector',
      category: 'Audio/Visual',
      location: 'Main Auditorium',
      nextDueAt: '2026-10-14',
      tagNumber: 'AV-012',
      timing: 'in 14 days',
    },
  },
  'asset-overdue-reminder': {
    category: EmailCategory.ASSET_ALERTS,
    label: 'Asset return overdue',
    description:
      'Sent when checked-out equipment has not been returned on time.',
    lockedNote: 'The overdue notice and asset details are always included.',
    subject: '{{default_subject}}',
    heading: 'Overdue Asset Return',
    message: '<p>Hi {{recipient_name}},</p>',
    closing:
      '<p>If you have already returned this asset, please ignore this message or contact your church administrator to update the records.</p>',
    signoff: '',
    signature: '',
    preheader:
      'Overdue asset reminder: {{asset_name}} ({{tag_number}}) was due on {{expected_return_at}} — {{days_overdue}} day(s) ago.',
    placeholders: {
      default_subject: 'Asset return overdue',
      asset_name: 'Projector',
      category: 'Audio/Visual',
      checked_out_at: '2026-09-20',
      days_overdue: '3',
      expected_return_at: '2026-09-27',
      location: 'Main Auditorium',
      purpose: 'Youth programme',
      recipient_name: 'Tunde Bello',
      tag_number: 'AV-012',
    },
    toVars: pick({
      asset_name: 'assetName',
      category: 'category',
      checked_out_at: 'checkedOutAt',
      days_overdue: 'daysOverdue',
      expected_return_at: 'expectedReturnAt',
      location: 'location',
      purpose: 'purpose',
      recipient_name: 'recipientName',
      tag_number: 'tagNumber',
    }),
    sampleData: {
      assetName: 'Projector',
      category: 'Audio/Visual',
      checkedOutAt: '2026-09-20',
      daysOverdue: '3',
      expectedReturnAt: '2026-09-27',
      location: 'Main Auditorium',
      purpose: 'Youth programme',
      recipientName: 'Tunde Bello',
      tagNumber: 'AV-012',
    },
  },
  'asset-return-notification': {
    category: EmailCategory.ASSET_ALERTS,
    label: 'Asset returned',
    description: 'Sent when checked-out equipment is returned.',
    lockedNote: 'The return notice and asset details are always included.',
    subject: '{{default_subject}}',
    heading: 'Asset Return Confirmed',
    message: '<p>Hi {{recipient_name}},</p>',
    closing:
      '<p>If you believe this is an error, please contact your church administrator.</p>',
    signoff: '',
    signature: '',
    preheader:
      'Asset return confirmed: {{asset_name}} ({{tag_number}}) was returned on {{returned_at}} .',
    placeholders: {
      default_subject: 'Asset returned',
      asset_name: 'Projector',
      category: 'Audio/Visual',
      checked_out_at: '2026-09-20',
      location: 'Main Auditorium',
      recipient_name: 'Tunde Bello',
      returned_at: '2026-09-28',
      returned_by: 'Tunde Bello',
      tag_number: 'AV-012',
    },
    toVars: pick({
      asset_name: 'assetName',
      category: 'category',
      checked_out_at: 'checkedOutAt',
      location: 'location',
      recipient_name: 'recipientName',
      returned_at: 'returnedAt',
      returned_by: 'returnedBy',
      tag_number: 'tagNumber',
    }),
    sampleData: {
      assetName: 'Projector',
      category: 'Audio/Visual',
      checkedOutAt: '2026-09-20',
      location: 'Main Auditorium',
      recipientName: 'Tunde Bello',
      returnedAt: '2026-09-28',
      returnedBy: 'Tunde Bello',
      tagNumber: 'AV-012',
    },
  },
  'asset-vehicle-expiry-alert': {
    category: EmailCategory.ASSET_ALERTS,
    label: 'Vehicle document expiring',
    description: "Sent before a church vehicle's document expires.",
    lockedNote: 'The expiry notice and vehicle details are always included.',
    subject: '{{default_subject}}',
    heading: '{{doc_label}} Expiry Notice',
    message:
      '<p>This is a reminder to renew the {{doc_label}} certificate before it expires to ensure the vehicle remains compliant and roadworthy.</p>',
    closing: '',
    signoff: '',
    signature: '',
    preheader:
      '{{doc_label}} Expiring in {{timing}}: {{asset_name}} — expires on {{expiry_date}}.',
    placeholders: {
      default_subject: 'Vehicle document expiring',
      asset_name: 'Projector',
      category: 'Audio/Visual',
      doc_label: 'Insurance',
      expiry_date: '2026-10-14',
      location: 'Main Auditorium',
      tag_number: 'AV-012',
      timing: 'in 14 days',
    },
    toVars: pick({
      asset_name: 'assetName',
      category: 'category',
      doc_label: 'docLabel',
      expiry_date: 'expiryDate',
      location: 'location',
      tag_number: 'tagNumber',
      timing: 'timing',
    }),
    sampleData: {
      assetName: 'Projector',
      category: 'Audio/Visual',
      docLabel: 'Insurance',
      expiryDate: '2026-10-14',
      location: 'Main Auditorium',
      tagNumber: 'AV-012',
      timing: 'in 14 days',
    },
  },
  'asset-warranty-alert': {
    category: EmailCategory.ASSET_ALERTS,
    label: 'Asset warranty expiring',
    description: "Sent before equipment's warranty expires.",
    lockedNote: 'The warranty notice and asset details are always included.',
    subject: '{{default_subject}}',
    heading: 'Warranty Expiry Notice',
    message:
      "<p>This is a reminder to review the asset's warranty coverage and take any necessary action before it expires.</p>",
    closing: '',
    signoff: '',
    signature: '',
    preheader:
      'Warranty Expiring in {{timing}}: {{asset_name}} — warranty expires on {{warranty_expiry}} .',
    placeholders: {
      default_subject: 'Asset warranty expiring',
      asset_name: 'Projector',
      category: 'Audio/Visual',
      location: 'Main Auditorium',
      tag_number: 'AV-012',
      timing: 'in 14 days',
      vendor_contact: 'support@soundco.example',
      vendor_name: 'Sound Co.',
      warranty_expiry: '2026-10-14',
    },
    toVars: pick({
      asset_name: 'assetName',
      category: 'category',
      location: 'location',
      tag_number: 'tagNumber',
      timing: 'timing',
      vendor_contact: 'vendorContact',
      vendor_name: 'vendorName',
      warranty_expiry: 'warrantyExpiry',
    }),
    sampleData: {
      assetName: 'Projector',
      category: 'Audio/Visual',
      location: 'Main Auditorium',
      tagNumber: 'AV-012',
      timing: 'in 14 days',
      vendorContact: 'support@soundco.example',
      vendorName: 'Sound Co.',
      warrantyExpiry: '2026-10-14',
    },
  },
  'checkin-confirmation': {
    category: EmailCategory.ATTENDANCE_CHECKIN,
    label: 'Check-in confirmation',
    description: 'Sent to a member after they check in to a service.',
    lockedNote: 'The service and check-in details are always included.',
    subject: '{{default_subject}}',
    heading: 'Check-in Confirmed, {{first_name}}!',
    message: "<p>You've successfully checked in. Here are the details:</p>",
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader: 'Check-in confirmed for {{service_name}} on {{event_date}}.',
    placeholders: {
      default_subject: 'Check-in confirmation',
      checkin_time: '08:52',
      event_date: '2026-10-04',
      first_name: 'Ada',
      service_name: 'Sunday Service',
      slot_time: '09:00',
      status: 'On time',
    },
    toVars: pick({
      checkin_time: 'checkinTime',
      event_date: 'eventDate',
      first_name: 'name',
      service_name: 'serviceName',
      slot_time: 'slotTime',
      status: 'status',
    }),
    sampleData: {
      checkinTime: '08:52',
      eventDate: '2026-10-04',
      name: 'Ada',
      serviceName: 'Sunday Service',
      slotTime: '09:00',
      status: 'On time',
    },
  },
  'class-guest-access': {
    category: null,
    group: 'Classes',
    label: 'Class guest access link',
    description: 'Sent to a guest enrolled in a class, with their portal link.',
    lockedNote: 'The portal link and button are always included.',
    subject: '{{default_subject}}',
    heading: 'Welcome, {{first_name}}!',
    message:
      "<p>You've been enrolled in <strong>{{class_name}}</strong> at {{church_name}}. You don't need an account to take part — use the link below any time to view your assignments and submit your work.</p>",
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader:
      "You're enrolled in {{class_name}} at {{church_name}} — here's your link to view assignments.",
    placeholders: {
      default_subject: 'Class guest access link',
      class_name: 'Foundation Class',
      first_name: 'Ada',
      portal_url: 'https://example.com/classes',
    },
    toVars: pick({
      class_name: 'className',
      first_name: 'name',
      portal_url: 'portalUrl',
    }),
    sampleData: {
      className: 'Foundation Class',
      name: 'Ada',
      portalUrl: 'https://example.com/classes',
    },
  },
  'class-level-promotion': {
    category: null,
    group: 'Classes',
    label: 'Moved up a class level',
    description: 'Sent when a member is promoted to the next class level.',
    lockedNote: 'Nothing is locked — the whole message is yours.',
    subject: '{{default_subject}}',
    heading: 'Congratulations, {{first_name}}!',
    message:
      "<p>Having completed <strong>{{from_class_name}}</strong>, you've been enrolled in <strong>{{to_class_name}}</strong> — the next level in your class progression.</p><p>We look forward to seeing you continue growing with us.</p>",
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader:
      "You've been promoted to the next class level at {{church_name}}.",
    placeholders: {
      default_subject: 'Moved up a class level',
      from_class_name: 'Foundation Class',
      first_name: 'Ada',
      to_class_name: 'Maturity Class',
    },
    toVars: pick({
      from_class_name: 'fromClassName',
      first_name: 'name',
      to_class_name: 'toClassName',
    }),
    sampleData: {
      fromClassName: 'Foundation Class',
      name: 'Ada',
      toClassName: 'Maturity Class',
    },
  },
  'device-reset-confirmation': {
    category: null,
    label: 'Device reset confirmed',
    description:
      'Sent after a member resets the device their account is locked to.',
    lockedNote: 'The security notice is always included.',
    subject: '{{default_subject}}',
    heading: 'Device Updated',
    message:
      '<p>Hi {{first_name}},</p><p>Your registered device has been successfully changed. All previous sessions have been invalidated. You can now sign in from your new device.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Dev Team',
    preheader: 'Your registered device has been changed on your account.',
    placeholders: {
      default_subject: 'Device reset confirmed',
      first_name: 'Ada',
    },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'device-reset-otp': {
    category: null,
    label: 'Device reset code',
    description:
      'Sent with the one-time code to reset the device an account is locked to.',
    lockedNote: 'The one-time code and security notice are always included.',
    subject: '{{default_subject}}',
    heading: 'Device Reset Request',
    message:
      '<p>Hi {{first_name}},</p><p>We received a request to link a new device to your account. Use the code below to confirm this change:</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Dev Team',
    preheader: '',
    placeholders: {
      default_subject: 'Device reset code',
      expires_minutes: '10',
      first_name: 'Ada',
    },
    toVars: pick({ expires_minutes: 'expiresMinutes', first_name: 'name' }),
    sampleData: { expiresMinutes: '10', name: 'Ada', otp: '482913' },
  },
  'email-change-otp': {
    category: null,
    label: 'Email change code',
    description: 'Sent with the one-time code to confirm a new email address.',
    lockedNote: 'The one-time code and security notice are always included.',
    subject: '{{default_subject}}',
    heading: 'Confirm Your New Email Address',
    message:
      '<p>Hi {{first_name}},</p><p>You asked to change the email address on your account to this one. Use the code below in the app to confirm the change:</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Dev Team',
    preheader: 'Confirm your new email address for {{church_name}}.',
    placeholders: {
      default_subject: 'Email change code',
      expires_minutes: '10',
      first_name: 'Ada',
    },
    toVars: pick({ expires_minutes: 'expiresMinutes', first_name: 'name' }),
    sampleData: { expiresMinutes: '10', name: 'Ada', otp: '482913' },
  },
  'email-changed-confirmation': {
    category: null,
    label: 'Email address changed',
    description: "Sent to confirm a member's email address was changed.",
    lockedNote: 'The security notice is always included.',
    subject: '{{default_subject}}',
    heading: 'Email Address Updated',
    message:
      '<p>Hi {{first_name}},</p><p>This is confirmation that your account email address has been changed to this one. Use it the next time you sign in.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Dev Team',
    preheader: 'Your account email address has been updated.',
    placeholders: {
      default_subject: 'Email address changed',
      first_name: 'Ada',
    },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'finance-proof-attached': {
    category: null,
    group: 'Finance requests',
    label: 'Finance request proof attached',
    description:
      'Sent to a department head when proof is attached to their finance request.',
    lockedNote: 'The request details and proof link are always included.',
    subject: '{{default_subject}}',
    heading: 'Payment Proof Available, {{first_name}}',
    message:
      '<p>The finance team has attached proof of payment to your approved finance request.</p>',
    closing:
      '<p>Please log in to the app to view the full details of your request.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Payment proof has been attached to your finance request.',
    placeholders: {
      default_subject: 'Finance request proof attached',
      amount: 'NGN 50,000',
      first_name: 'Ada',
      proof_url: 'https://example.com/proof',
      reason: 'Sound equipment repair',
    },
    toVars: pick({
      amount: 'amount',
      first_name: 'name',
      proof_url: 'proofUrl',
      reason: 'reason',
    }),
    sampleData: {
      amount: 'NGN 50,000',
      name: 'Ada',
      proofUrl: 'https://example.com/proof',
      reason: 'Sound equipment repair',
    },
  },
  'finance-request-approved': {
    category: null,
    group: 'Finance requests',
    label: 'Finance request approved',
    description: 'Sent when a finance request is approved.',
    lockedNote: 'The request details are always included.',
    subject: '{{default_subject}}',
    heading: 'Finance Request Approved, {{first_name}}',
    message:
      '<p>Great news! Your finance request has been approved by the finance team.</p>',
    closing:
      '<p>The finance team will process the payment and attach proof of payment when completed. You will receive another notification at that point.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your finance request of {{amount}} has been approved.',
    placeholders: {
      default_subject: 'Finance request approved',
      amount: 'NGN 50,000',
      first_name: 'Ada',
      reason: 'Sound equipment repair',
    },
    toVars: pick({ amount: 'amount', first_name: 'name', reason: 'reason' }),
    sampleData: {
      amount: 'NGN 50,000',
      name: 'Ada',
      reason: 'Sound equipment repair',
    },
  },
  'finance-request-rejected': {
    category: null,
    group: 'Finance requests',
    label: 'Finance request declined',
    description: 'Sent when a finance request is declined.',
    lockedNote: 'The request details and reason are always included.',
    subject: '{{default_subject}}',
    heading: 'Finance Request Not Approved, {{first_name}}',
    message:
      '<p>Unfortunately, your finance request has not been approved at this time.</p>',
    closing:
      '<p>If you have any questions, please reach out to the finance team directly.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your finance request of {{amount}} was not approved.',
    placeholders: {
      default_subject: 'Finance request declined',
      amount: 'NGN 50,000',
      first_name: 'Ada',
      reason: 'Sound equipment repair',
      rejection_reason: 'Budget exceeded for this month',
    },
    toVars: pick({
      amount: 'amount',
      first_name: 'name',
      reason: 'reason',
      rejection_reason: 'rejectionReason',
    }),
    sampleData: {
      amount: 'NGN 50,000',
      name: 'Ada',
      reason: 'Sound equipment repair',
      rejectionReason: 'Budget exceeded for this month',
    },
  },
  'finance-request-submitted': {
    category: null,
    group: 'Finance requests',
    label: 'Finance request submitted',
    description: 'Sent to finance approvers when a new request is submitted.',
    lockedNote: 'The request details are always included.',
    subject: '{{default_subject}}',
    heading: 'New Finance Request',
    message:
      '<p>A new finance request has been submitted and is pending your review.</p>',
    closing:
      '<p>Please log in to the admin portal to review and take action on this request.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'A new finance request of {{amount}} is awaiting your review.',
    placeholders: {
      default_subject: 'Finance request submitted',
      amount: 'NGN 50,000',
      reason: 'Sound equipment repair',
      request_id: 'FR-1042',
    },
    toVars: pick({
      amount: 'amount',
      reason: 'reason',
      request_id: 'requestId',
    }),
    sampleData: {
      amount: 'NGN 50,000',
      reason: 'Sound equipment repair',
      requestId: 'FR-1042',
    },
  },
  'follow-up-overdue-admin': {
    category: EmailCategory.FOLLOW_UP,
    label: 'Overdue follow-ups (admin)',
    description: 'Sent to admins when follow-up tasks are overdue.',
    lockedNote: 'The task count and button are always included.',
    subject: '{{default_subject}}',
    heading: 'Overdue Tasks Alert, {{admin_name}}',
    message:
      '<p>There are currently <strong>{{count}} overdue follow-up task(s)</strong> across the follow-up team.</p>',
    closing:
      '<p>Please review the Follow-Up dashboard to reassign or escalate where needed.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: '{{count}} overdue follow-up task(s) need your review.',
    placeholders: {
      default_subject: 'Overdue follow-ups (admin)',
      admin_name: 'Tunde',
      count: '3',
    },
    toVars: pick({ admin_name: 'adminName', count: 'count' }),
    sampleData: { adminName: 'Tunde', count: '3' },
  },
  'follow-up-overdue-worker': {
    category: EmailCategory.FOLLOW_UP,
    label: 'Overdue follow-ups (worker)',
    description: 'Sent to a Follow-Up worker whose tasks are overdue.',
    lockedNote: 'The list of overdue tasks is always included.',
    subject: '{{default_subject}}',
    heading: 'Overdue Tasks, {{worker_name}}',
    message:
      '<p>You have <strong>{{count}} overdue follow-up task(s)</strong> that require your immediate attention. Please log in and update these as soon as possible.</p>',
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader:
      'You have {{count}} overdue follow-up task(s) that need your attention.',
    placeholders: {
      default_subject: 'Overdue follow-ups (worker)',
      count: '3',
      worker_name: 'Tunde',
    },
    toVars: pick({ count: 'count', worker_name: 'workerName' }),
    sampleData: { count: '3', workerName: 'Tunde' },
  },
  'follow-up-stale-admin': {
    category: EmailCategory.FOLLOW_UP,
    label: 'Stale follow-ups (admin)',
    description:
      "Sent to admins when first-timers haven't been contacted for a while.",
    lockedNote: 'The first-timer count and button are always included.',
    subject: '{{default_subject}}',
    heading: 'Inactive Tasks Alert, {{admin_name}}',
    message:
      '<p>There are currently <strong>{{count}} follow-up task(s)</strong> with no activity for <strong>{{stale_days}}+ day(s)</strong> across the follow-up team.</p>',
    closing:
      '<p>Please review the Follow-Up dashboard to reassign or escalate where needed.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader:
      '{{count}} follow-up task(s) have had no activity for {{stale_days}}+ day(s).',
    placeholders: {
      default_subject: 'Stale follow-ups (admin)',
      admin_name: 'Tunde',
      count: '3',
      stale_days: '7',
    },
    toVars: pick({
      admin_name: 'adminName',
      count: 'count',
      stale_days: 'staleDays',
    }),
    sampleData: { adminName: 'Tunde', count: '3', staleDays: '7' },
  },
  'follow-up-task-assigned': {
    category: EmailCategory.FOLLOW_UP,
    label: 'Follow-up task assigned',
    description:
      'Sent to a Follow-Up worker when a first-timer is assigned to them.',
    lockedNote:
      "The first-timer's contact details and due date are always included.",
    subject: '{{default_subject}}',
    heading: 'New Task Assigned, {{worker_name}}!',
    message:
      '<p>A new follow-up task has been assigned to you. Please reach out to this visitor as soon as possible.</p>',
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader:
      'New follow-up task assigned — please reach out to {{first_timer_name}}.',
    placeholders: {
      default_subject: 'Follow-up task assigned',
      due_date: '2026-10-05',
      first_timer_email: 'chidi@example.com',
      first_timer_name: 'Chidi Okeke',
      first_timer_phone: '+2348098765432',
      worker_name: 'Tunde',
    },
    toVars: pick({
      due_date: 'dueDate',
      first_timer_email: 'email',
      first_timer_name: 'firstTimerName',
      first_timer_phone: 'phone',
      worker_name: 'workerName',
    }),
    sampleData: {
      dueDate: '2026-10-05',
      email: 'ada@example.com',
      firstTimerName: 'Chidi Okeke',
      phone: '+2348012345678',
      workerName: 'Tunde',
    },
  },
  'forgot-password-otp': {
    category: null,
    label: 'Password reset code',
    description: 'Sent with the one-time code to reset a forgotten password.',
    lockedNote: 'The one-time code and expiry are always included.',
    subject: '{{default_subject}}',
    heading: 'Password Reset Code, {{first_name}}',
    message:
      '<p>We received a request to reset the password for your account. Use the code below to reset your password.</p>',
    closing:
      '<p>If you did not request a password reset, please ignore this email. Your account is safe and no changes have been made.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your {{church_name}} password reset code.',
    placeholders: {
      default_subject: 'Password reset code',
      expires_minutes: '10',
      first_name: 'Ada',
    },
    toVars: pick({ expires_minutes: 'expiresMinutes', first_name: 'name' }),
    sampleData: { expiresMinutes: '10', name: 'Ada', otp: '482913' },
  },
  'form-submission-new': {
    category: EmailCategory.FORM_SUBMISSION,
    label: 'New form submission',
    description: 'Sent to admins when someone submits a form.',
    lockedNote: 'The submission details are always included.',
    subject: '{{default_subject}}',
    heading: 'New Form Submission',
    message:
      "<p>A new submission has come in for a form you're notified on. Log in to your admin portal to view the full response.</p>",
    closing: '',
    signoff: 'Regards,',
    signature: '{{church_name}} System',
    preheader: 'A new form submission has come in and requires your attention.',
    placeholders: {
      default_subject: 'New form submission',
      form_title: 'Volunteer Sign-up',
      submission_id: 'SUB-381',
    },
    toVars: pick({ form_title: 'formTitle', submission_id: 'submissionId' }),
    sampleData: { formTitle: 'Volunteer Sign-up', submissionId: 'SUB-381' },
  },
  'incident-report-new': {
    category: EmailCategory.INCIDENT_REPORT,
    label: 'New incident report',
    description: 'Sent to admins when an incident is reported.',
    lockedNote: 'The report details are always included.',
    subject: '{{default_subject}}',
    heading: 'New Incident Report',
    message:
      '<p>A new incident has been reported and is awaiting review. Please log in to your admin portal to view the full details and take action.</p>',
    closing: '',
    signoff: 'Regards,',
    signature: '{{church_name}} System',
    preheader:
      'A new incident report has been submitted and requires your attention.',
    placeholders: {
      default_subject: 'New incident report',
      location: 'Main Auditorium',
      report_id: 'IR-77',
      title: 'Broken pew in row 4',
    },
    toVars: pick({
      location: 'location',
      report_id: 'reportId',
      title: 'title',
    }),
    sampleData: {
      location: 'Main Auditorium',
      reportId: 'IR-77',
      title: 'Broken pew in row 4',
    },
  },
  'leave-actioned': {
    category: null,
    group: 'Workforce',
    label: 'Leave request decided',
    description:
      'Sent to a worker when their leave request is approved or declined.',
    lockedNote: 'The leave dates and decision are always included.',
    subject: '{{default_subject}}',
    heading: 'Leave Request {{action_status}}, {{first_name}}',
    message:
      '<p>Your leave request has been reviewed. Here is the outcome:</p>',
    closing:
      '<p>If you have any questions, please speak to your department lead or contact the admin team.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your leave request has been {{action_status}}.',
    placeholders: {
      default_subject: 'Leave request decided',
      action_status: 'approved',
      date_from: '2026-10-10',
      date_to: '2026-10-17',
      first_name: 'Ada',
    },
    toVars: pick({
      action_status: 'actionStatus',
      date_from: 'dateFrom',
      date_to: 'dateTo',
      first_name: 'name',
    }),
    sampleData: {
      actionStatus: 'approved',
      dateFrom: '2026-10-10',
      dateTo: '2026-10-17',
      name: 'Ada',
    },
  },
  'leave-submitted': {
    category: null,
    group: 'Workforce',
    label: 'Leave request submitted',
    description: 'Sent to a department head when a worker requests leave.',
    lockedNote: 'The leave dates are always included.',
    subject: '{{default_subject}}',
    heading: 'Leave Request Received, {{first_name}}',
    message:
      '<p>Your leave request has been submitted successfully and is pending review.</p>',
    closing:
      '<p>You will receive another email once a decision has been made.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader:
      'Your leave request from {{date_from}} to {{date_to}} has been received.',
    placeholders: {
      default_subject: 'Leave request submitted',
      date_from: '2026-10-10',
      date_to: '2026-10-17',
      first_name: 'Ada',
      reason: 'Sound equipment repair',
    },
    toVars: pick({
      date_from: 'dateFrom',
      date_to: 'dateTo',
      first_name: 'name',
      reason: 'reason',
    }),
    sampleData: {
      dateFrom: '2026-10-10',
      dateTo: '2026-10-17',
      name: 'Ada',
      reason: 'Sound equipment repair',
    },
  },
  'login-notification': {
    category: EmailCategory.LOGIN_ALERT,
    label: 'New sign-in',
    description: 'Sent when a member signs in from a new device.',
    lockedNote: 'The sign-in time and security notice are always included.',
    subject: '{{default_subject}}',
    heading: 'New Login, {{first_name}}',
    message: '<p>We detected a new login to your {{church_name}} account.</p>',
    closing:
      '<p>If this was you, no action is needed.</p><p>If you did not log in, please contact an admin immediately to secure your account.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'A new login was detected on your account at {{login_time}}.',
    placeholders: {
      default_subject: 'New sign-in',
      login_time: '2026-09-30 08:15',
      first_name: 'Ada',
    },
    toVars: pick({ login_time: 'loginTime', first_name: 'name' }),
    sampleData: { loginTime: '2026-09-30 08:15', name: 'Ada' },
  },
  'login-security-alert': {
    category: null,
    label: 'Too many sign-in attempts',
    description:
      'Sent when an account is temporarily locked after failed sign-ins.',
    lockedNote: 'The lockout details and security notice are always included.',
    subject: '{{default_subject}}',
    heading: 'Security Alert, {{first_name}}',
    message:
      '<p>We detected multiple failed login attempts on your account. To protect your account, we have temporarily locked it.</p>',
    closing:
      '<p>Your account will be automatically unlocked after {{lockout_minutes}} minutes. You do not need to contact anyone if you triggered this yourself.</p><p><strong style="font-weight: 600;">If this was not you</strong>, someone may be attempting to access your account. Please contact an admin immediately to secure your account and change your password.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Dev Team',
    preheader: '',
    placeholders: {
      default_subject: 'Too many sign-in attempts',
      lockout_minutes: '15',
      first_name: 'Ada',
    },
    toVars: pick({ lockout_minutes: 'lockoutMinutes', first_name: 'name' }),
    sampleData: { lockoutMinutes: '15', name: 'Ada' },
  },
  'online-attendance-request': {
    category: EmailCategory.FOLLOW_UP,
    label: 'Online attendance check',
    description: 'Sent after a service to members marked as watching online.',
    lockedNote: 'The response buttons are always included.',
    subject: '{{default_subject}}',
    heading: 'Did You Join Us Online, {{first_name}}?',
    message:
      "<p>We noticed you didn't check in physically for <strong>{{event_name}}</strong>. Did you join us online?</p><p>If you attended online, please confirm your attendance using the app within the next <strong>{{window_hours}} hour(s)</strong>.</p>",
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader: 'Did you attend {{event_name}} online? Let us know!',
    placeholders: {
      default_subject: 'Online attendance check',
      event_name: 'Sunday Service',
      first_name: 'Ada',
      window_hours: '48',
    },
    toVars: pick({
      event_name: 'eventName',
      first_name: 'name',
      window_hours: 'windowHours',
    }),
    sampleData: { eventName: 'Sunday Service', name: 'Ada', windowHours: '48' },
  },
  'password-changed': {
    category: null,
    label: 'Password changed',
    description: "Sent to confirm a member's password was changed.",
    lockedNote: 'The security notice is always included.',
    subject: '{{default_subject}}',
    heading: 'Password Changed, {{first_name}}',
    message:
      '<p>Your password was changed successfully. You can now log in with your new password.</p><p>If you did not make this change, please contact an admin immediately as your account may have been compromised.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your {{church_name}} password has been changed successfully.',
    placeholders: { default_subject: 'Password changed', first_name: 'Ada' },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'password-reset': {
    category: null,
    label: 'Password reset by admin',
    description:
      "Sent with a new temporary password when an admin resets a member's password.",
    lockedNote: 'The temporary password and sign-in link are always included.',
    subject: '{{default_subject}}',
    heading: 'Password Reset, {{first_name}}',
    message:
      '<p>An admin has reset your password. Please log in with the temporary password below and change it immediately.</p>',
    closing:
      '<p>If you did not request this reset, please contact an admin immediately.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your {{church_name}} password has been reset by an admin.',
    placeholders: {
      default_subject: 'Password reset by admin',
      first_name: 'Ada',
    },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada', newPassword: '••••••••' },
  },
  'pastor-feedback-reminder': {
    category: EmailCategory.PASTOR_FEEDBACK,
    label: 'Weekly feedback reminder',
    description:
      "Reminds a department lead to submit the week's pastor feedback.",
    lockedNote: 'The feedback button is always included.',
    subject: '{{default_subject}}',
    heading: 'Weekly Feedback Reminder, {{first_name}}',
    message:
      "<p>The week of <strong>{{week_of}}</strong> has closed and <strong>{{department_name}}</strong> hasn't submitted its weekly feedback yet.</p><p>Please log in and share your department's attendance notes, highlights, challenges, and any prayer requests for the pastorate to review.</p>",
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader:
      "Weekly feedback for {{department_name}} hasn't been submitted yet.",
    placeholders: {
      default_subject: 'Weekly feedback reminder',
      department_name: 'Media',
      first_name: 'Ada',
      week_of: '2026-09-28',
    },
    toVars: pick({
      department_name: 'departmentName',
      first_name: 'name',
      week_of: 'weekOf',
    }),
    sampleData: { departmentName: 'Media', name: 'Ada', weekOf: '2026-09-28' },
  },
  'pastor-feedback-response': {
    category: EmailCategory.PASTOR_FEEDBACK,
    label: 'Pastor responded to feedback',
    description:
      'Sent to the submitter when a pastor responds to their feedback.',
    lockedNote: "The pastor's response is always included.",
    subject: '{{default_subject}}',
    heading: 'Pastor Response, {{first_name}}',
    message:
      "<p>A pastor responded to <strong>{{department_name}}</strong>'s feedback for the week of <strong>{{week_of}}</strong>:</p>",
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'A pastor responded to your {{department_name}} feedback.',
    placeholders: {
      default_subject: 'Pastor responded to feedback',
      department_name: 'Media',
      first_name: 'Ada',
      response: 'Thank you — great work this week.',
      week_of: '2026-09-28',
    },
    toVars: pick({
      department_name: 'departmentName',
      first_name: 'name',
      response: 'response',
      week_of: 'weekOf',
    }),
    sampleData: {
      departmentName: 'Media',
      name: 'Ada',
      response: 'Thank you — great work this week.',
      weekOf: '2026-09-28',
    },
  },
  'pledge-contribution-declined': {
    category: EmailCategory.GIVING_RECEIPT,
    label: 'Pledge payment declined',
    description: "Sent when the finance team can't confirm a pledge payment.",
    lockedNote:
      "The payment details and the finance team's note are always included.",
    subject: '{{default_subject}}',
    heading: 'Pledge Payment Update',
    message:
      '<p>Dear {{first_name}},</p><p>We were unable to confirm the payment you logged against your pledge to <span style="font-weight: 500;">{{campaign_name}}</span>.</p>',
    closing:
      '<p>If you believe this is an error, please speak with a member of the finance team.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Finance Team',
    preheader: '',
    placeholders: {
      default_subject: 'Pledge payment declined',
      amount: 'NGN 50,000',
      campaign_name: 'Building Fund',
      finance_note: 'We could not match this transfer.',
      first_name: 'Ada',
      payment_date: '2026-09-27',
    },
    toVars: pick({
      amount: 'amount',
      campaign_name: 'campaignName',
      finance_note: 'financeNote',
      first_name: 'name',
      payment_date: 'paymentDate',
    }),
    sampleData: {
      amount: 'NGN 50,000',
      campaignName: 'Building Fund',
      financeNote: 'We could not match this transfer.',
      name: 'Ada',
      paymentDate: '2026-09-27',
    },
  },
  'prayer-reminder': {
    category: EmailCategory.PRAYER_REMINDER,
    label: 'Prayer meeting reminder',
    description: 'Sent before a prayer meeting someone is scheduled for.',
    lockedNote: 'The meeting date, time and mode are always included.',
    subject: '{{default_subject}}',
    heading: 'Prayer Meeting Reminder',
    message: '<p>Hi {{first_name}},</p>',
    closing:
      '<p>Your commitment to this ministry is valued. Thank you for showing up.</p>',
    signoff: 'God bless you,',
    signature: '{{church_name}} Team',
    preheader:
      'Prayer meeting reminder for {{meeting_date}} — {{start_time}} to {{end_time}}',
    placeholders: {
      default_subject: 'Prayer meeting reminder',
      end_time: '07:00',
      meeting_date: '2026-10-04',
      mode: 'Online',
      first_name: 'Ada',
      start_time: '06:00',
    },
    toVars: pick({
      end_time: 'end_time',
      meeting_date: 'meeting_date',
      mode: 'mode',
      first_name: 'name',
      start_time: 'start_time',
    }),
    sampleData: {
      end_time: '07:00',
      meeting_date: '2026-10-04',
      mode: 'Online',
      name: 'Ada',
      start_time: '06:00',
    },
  },
  'service-programme-assignments': {
    category: null,
    group: 'Workforce',
    label: 'Service programme assignments',
    description:
      "Sent with all of a member's slots when a service programme is published.",
    lockedNote: 'The list of assignments is always included.',
    subject: '{{default_subject}}',
    heading: '',
    message:
      '<p>Please be ready and reach out to the service coordinator if you have any questions.</p>',
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader: "You've been added to the order of service.",
    placeholders: {
      default_subject: 'Service programme assignments',
      count: '3',
      member_name: 'Ada',
    },
    toVars: pick({ count: 'count', member_name: 'memberName' }),
    sampleData: { count: '3', memberName: 'Ada' },
  },
  'service-slot-assigned': {
    category: EmailCategory.SERVICE_PROGRAMME_ASSIGNMENT,
    label: 'Added to a service programme',
    description: 'Sent when someone is given a slot in a service programme.',
    lockedNote: 'The slot details are always included.',
    subject: '{{default_subject}}',
    heading: '',
    message:
      '<p>Please be ready and reach out to the service coordinator if you have any questions.</p>',
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader:
      "You've been added to the order of service for {{service_slot_name}}.",
    placeholders: {
      default_subject: 'Added to a service programme',
      allocated_minutes: '10',
      member_name: 'Ada',
      service_date: '2026-10-04',
      service_slot_name: 'Sunday Service',
      service_time: '09:00',
      slot_type: 'Scripture Reading',
      topic: 'Walking in faith',
    },
    toVars: pick({
      allocated_minutes: 'allocatedMinutes',
      member_name: 'memberName',
      service_date: 'serviceDate',
      service_slot_name: 'serviceSlotName',
      service_time: 'serviceTime',
      slot_type: 'slotType',
      topic: 'topic',
    }),
    sampleData: {
      allocatedMinutes: '10',
      memberName: 'Ada',
      serviceDate: '2026-10-04',
      serviceSlotName: 'Sunday Service',
      serviceTime: '09:00',
      slotType: 'Scripture Reading',
      topic: 'Walking in faith',
    },
  },
  'service-slot-reminder': {
    category: EmailCategory.SERVICE_PROGRAMME_ASSIGNMENT,
    label: 'Service slot reminder',
    description: "Sent before someone's slot in a service programme.",
    lockedNote: 'The slot details are always included.',
    subject: '{{default_subject}}',
    heading: "Reminder, {{member_name}} — you're on tomorrow's programme!",
    message:
      "<p>This is a reminder that you're on the order of service for <strong>{{service_slot_name}}</strong>.</p>",
    closing:
      '<p>Please be ready and reach out to the service coordinator if you have any questions.</p>',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader:
      "Reminder: you're on the order of service for {{service_slot_name}}.",
    placeholders: {
      default_subject: 'Service slot reminder',
      allocated_minutes: '10',
      member_name: 'Ada',
      service_slot_name: 'Sunday Service',
      slot_type: 'Scripture Reading',
      topic: 'Walking in faith',
    },
    toVars: pick({
      allocated_minutes: 'allocatedMinutes',
      member_name: 'memberName',
      service_slot_name: 'serviceSlotName',
      slot_type: 'slotType',
      topic: 'topic',
    }),
    sampleData: {
      allocatedMinutes: '10',
      memberName: 'Ada',
      serviceSlotName: 'Sunday Service',
      slotType: 'Scripture Reading',
      topic: 'Walking in faith',
    },
  },
  'session-security-alert': {
    category: null,
    label: 'Session security alert',
    description: 'Sent when a sign-in session is ended for security reasons.',
    lockedNote: 'The sign-in button is always included.',
    subject: '{{default_subject}}',
    heading: 'Security Alert, {{first_name}}',
    message:
      '<p>We detected that someone attempted to use an already-expired session credential on your {{church_name}} account. To protect your account, we immediately signed out that session.</p><p><strong style="font-weight: 600;">If this was you</strong>, you can safely ignore this email and log in again below.</p><p><strong style="font-weight: 600;">If this was not you</strong>, your session credential may have been compromised. We strongly recommend you change your password immediately after logging in.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: '',
    placeholders: {
      default_subject: 'Session security alert',
      first_name: 'Ada',
    },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'sunday-school-question-answered': {
    category: null,
    group: 'Classes',
    label: 'Sunday School question answered',
    description: 'Sent to a student when their question gets an answer.',
    lockedNote: 'The question and answer are always included.',
    subject: '{{default_subject}}',
    heading: 'Your Question Was Answered, {{first_name}}',
    message: '<p>Your question in <strong>{{class_name}}</strong>:</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'Your question in {{class_name}} was answered.',
    placeholders: {
      default_subject: 'Sunday School question answered',
      answer_text: 'Grace is the unearned favour of God.',
      class_name: 'Foundation Class',
      first_name: 'Ada',
      question_text: 'What does grace mean?',
    },
    toVars: pick({
      answer_text: 'answerText',
      class_name: 'className',
      first_name: 'name',
      question_text: 'questionText',
    }),
    sampleData: {
      answerText: 'Grace is the unearned favour of God.',
      className: 'Foundation Class',
      name: 'Ada',
      questionText: 'What does grace mean?',
    },
  },
  'sunday-school-question-asked': {
    category: EmailCategory.SUNDAY_SCHOOL_QA,
    label: 'Sunday School question asked',
    description: "Sent to a class's teacher when a student asks a question.",
    lockedNote: 'The question is always included.',
    subject: '{{default_subject}}',
    heading: 'New Question, {{first_name}}',
    message:
      '<p><strong>{{asker_name}}</strong> asked a question in <strong>{{class_name}}</strong>:</p>',
    closing: '<p>Open the Sunday School section of the app to reply.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: '{{asker_name}} asked a question in {{class_name}}.',
    placeholders: {
      default_subject: 'Sunday School question asked',
      asker_name: 'Ada Obi',
      class_name: 'Foundation Class',
      first_name: 'Ada',
      question_text: 'What does grace mean?',
    },
    toVars: pick({
      asker_name: 'askerName',
      class_name: 'className',
      first_name: 'name',
      question_text: 'questionText',
    }),
    sampleData: {
      askerName: 'Ada Obi',
      className: 'Foundation Class',
      name: 'Ada',
      questionText: 'What does grace mean?',
    },
  },
  'thank-you-attendance': {
    category: EmailCategory.FOLLOW_UP,
    label: 'Thank you for attending',
    description: 'Sent after a service to thank members who attended.',
    lockedNote: 'Nothing is locked — the whole message is yours.',
    subject: '{{default_subject}}',
    heading: 'Thank You, {{first_name}}!',
    message:
      "<p>It was a blessing to have you join us at <strong>{{event_name}}</strong>. We're grateful you made time to worship with us.</p><p>We look forward to seeing you again soon. You are always welcome at {{church_name}}.</p>",
    closing: '',
    signoff: 'God bless you,',
    signature: '{{church_name}}',
    preheader: 'Thank you for joining us at {{event_name}}!',
    placeholders: {
      default_subject: 'Thank you for attending',
      event_name: 'Sunday Service',
      first_name: 'Ada',
    },
    toVars: pick({ event_name: 'eventName', first_name: 'name' }),
    sampleData: { eventName: 'Sunday Service', name: 'Ada' },
  },
  'tithe-proof-declined': {
    category: EmailCategory.GIVING_RECEIPT,
    label: 'Tithe payment declined',
    description:
      "Sent when the finance team can't confirm a tithe payment proof.",
    lockedNote:
      "The payment details and the finance team's note are always included.",
    subject: '{{default_subject}}',
    heading: 'Tithe Submission Update',
    message:
      '<p>Dear {{first_name}},</p><p>We were unable to confirm your recent tithe payment submission.</p>',
    closing:
      '<p>If you believe this is an error, please contact your bank and resubmit your proof. If you need further assistance, please speak with a member of the finance team.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Finance Team',
    preheader: '',
    placeholders: {
      default_subject: 'Tithe payment declined',
      amount: 'NGN 50,000',
      finance_note: 'We could not match this transfer.',
      first_name: 'Ada',
      payment_date: '2026-09-27',
    },
    toVars: pick({
      amount: 'amount',
      finance_note: 'financeNote',
      first_name: 'name',
      payment_date: 'paymentDate',
    }),
    sampleData: {
      amount: 'NGN 50,000',
      financeNote: 'We could not match this transfer.',
      name: 'Ada',
      paymentDate: '2026-09-27',
    },
  },
  'tithe-proof-submitted': {
    category: EmailCategory.GIVING_RECEIPT,
    label: 'Tithe proof received',
    description:
      'Sent to confirm a tithe payment proof was received for review.',
    lockedNote: 'The reference number is always included.',
    subject: '{{default_subject}}',
    heading: 'New Tithe Payment Proof',
    message:
      '<p>A member has submitted a tithe payment proof and is awaiting your review.</p>',
    closing:
      '<p>Please log in to the admin portal to confirm or decline this submission.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Finance Team',
    preheader:
      'A member has submitted a tithe payment proof and is awaiting your review.',
    placeholders: {
      default_subject: 'Tithe proof received',
      amount: 'NGN 50,000',
      payment_date: '2026-09-27',
      proof_id: 'TP-2231',
    },
    toVars: pick({
      amount: 'amount',
      payment_date: 'paymentDate',
      proof_id: 'proofId',
    }),
    sampleData: {
      amount: 'NGN 50,000',
      paymentDate: '2026-09-27',
      proofId: 'TP-2231',
    },
  },
  'tithe-statement': {
    category: EmailCategory.GIVING_RECEIPT,
    label: 'Giving statement',
    description: "Sent with a member's tithe or pledge statement attached.",
    lockedNote: 'The statement period and attachment note are always included.',
    subject: '{{default_subject}}',
    heading: '',
    message: '',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}} Finance Team',
    preheader: 'Your giving statement is attached to this email.',
    placeholders: {
      default_subject: 'Giving statement',
      count: '3',
      first_name: 'Ada',
      period: 'January – September 2026',
    },
    toVars: pick({ count: 'count', first_name: 'name', period: 'period' }),
    sampleData: { count: '3', name: 'Ada', period: 'January – September 2026' },
  },
  'trainee-demoted': {
    category: null,
    group: 'Workforce',
    label: 'Workforce training ended',
    description:
      "Sent when a trainee worker's training ends without promotion.",
    lockedNote: 'Nothing is locked — the whole message is yours.',
    subject: '{{default_subject}}',
    heading: 'Training Update, {{first_name}}',
    message:
      '<p>Your worker training period has ended and your worker role has been removed. You can still log in to the app as a member.</p><p>If you believe this was done in error, please contact an admin directly.</p><p>Thank you for your service to {{church_name}}.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'An update to your {{church_name}} training.',
    placeholders: {
      default_subject: 'Workforce training ended',
      first_name: 'Ada',
    },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'welcome-admin': {
    category: null,
    label: 'Welcome to a new admin',
    description:
      'Sent when someone is given admin access, with their sign-in details.',
    lockedNote:
      'Their temporary password and sign-in link are always included.',
    subject: '{{default_subject}}',
    heading: 'Welcome, {{first_name}}!',
    message:
      '<p>An admin account has been created for you on the {{church_name}} Staff platform. Your credentials are listed below.</p>',
    closing:
      '<p>If you did not expect this email or believe this was sent in error, please contact the system administrator immediately.</p>',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader:
      'Your admin account has been created. Please keep your credentials safe.',
    placeholders: {
      default_subject: 'Welcome to a new admin',
      email: 'ada@example.com',
      first_name: 'Ada',
    },
    toVars: pick({ email: 'email', first_name: 'name' }),
    sampleData: { email: 'ada@example.com', name: 'Ada', password: '••••••••' },
  },
  'welcome-worker': {
    category: null,
    group: 'Workforce',
    label: 'Welcome to a new worker',
    description:
      'Sent when a member is promoted to a worker, with getting-started links.',
    lockedNote:
      'The getting-started links and support details are always included.',
    subject: '{{default_subject}}',
    heading: 'Welcome, {{name}}!',
    message:
      "<p>We’re excited to let you know that you've been successfully onboarded to the {{church_name}} Staff platform.</p>",
    closing: '',
    signoff: '',
    signature: '',
    preheader:
      'Welcome to the {{church_name}} Workers platform. Here’s everything you need to get started!',
    placeholders: {
      default_subject: 'Welcome to a new worker',
      explainer_video_android_url: 'https://example.com/android',
      explainer_video_ios_url: 'https://example.com/ios',
      name: 'Ada',
      support_form_url: 'https://example.com/support',
      username: 'ada.obi',
    },
    toVars: pick({
      explainer_video_android_url: 'explainer_video_android_url',
      explainer_video_ios_url: 'explainer_video_ios_url',
      name: 'name',
      support_form_url: 'support_form_url',
      username: 'username',
    }),
    sampleData: {
      explainer_video_android_url: 'https://example.com/android',
      explainer_video_ios_url: 'https://example.com/ios',
      name: 'Ada',
      support_form_url: 'https://example.com/support',
      username: 'ada.obi',
    },
  },
  'worker-revoked': {
    category: null,
    group: 'Workforce',
    label: 'Worker access removed',
    description: "Sent when a member's worker status is removed.",
    lockedNote: 'Nothing is locked — the whole message is yours.',
    subject: '{{default_subject}}',
    heading: 'Worker Role Updated, {{first_name}}',
    message:
      '<p>Your worker role has been removed from our system. You can still log in to the app as a member. </p><p>If you believe this was done in error, please contact an admin directly.</p><p>Thank you for your service to {{church_name}}.</p>',
    closing: '',
    signoff: 'Sincerely,',
    signature: '{{church_name}}',
    preheader: 'An update to your {{church_name}} worker role.',
    placeholders: {
      default_subject: 'Worker access removed',
      first_name: 'Ada',
    },
    toVars: pick({ first_name: 'name' }),
    sampleData: { name: 'Ada' },
  },
  'annual-giving-statement': {
    category: null,
    group: 'Giving',
    label: 'Annual giving statement',
    description:
      "Sent each January with a member's giving total for the past year.",
    lockedNote: 'The yearly total and giving summary are always included.',
    subject: '{{default_subject}}',
    heading: '{{year}} Annual Giving Statement',
    message:
      '<p>Dear {{member_name}},</p><p>Thank you for your faithfulness and generosity to your church throughout {{year}}. This is your annual giving statement for your records.</p>',
    closing:
      "<p>Please retain this statement for your personal tax records. If you have any questions about your giving history, please contact the finance team.</p><p>God bless you for your continued support of your church's mission and vision.</p>",
    signoff: '',
    signature: '',
    preheader: 'Your {{year}} annual giving statement from your church.',
    placeholders: {
      default_subject: 'Annual giving statement',
      currency: 'NGN',
      line_count: '12',
      member_name: 'Ada',
      total: '600,000',
      year: '2025',
    },
    toVars: pick({
      currency: 'currency',
      line_count: 'lineCount',
      member_name: 'memberName',
      total: 'total',
      year: 'year',
    }),
    sampleData: {
      currency: 'NGN',
      lineCount: '12',
      memberName: 'Ada',
      total: '600,000',
      year: '2025',
    },
  },
  'child-pickup': {
    category: EmailCategory.CHILDREN_CHURCH,
    label: 'Child pickup confirmation',
    description:
      "Sent to a guardian when their child is picked up from Children's Church.",
    lockedNote:
      'The pickup details and the unauthorised-pickup notice are always included.',
    subject: '{{default_subject}}',
    heading: 'Pickup Confirmation',
    message:
      '<p>Dear {{guardian_name}},</p><p> This is to confirm that <span style="font-weight: 500;">{{child_name}}</span> has been safely picked up from Children\'s Church today. </p>',
    closing: '',
    signoff: 'Thank you for trusting us with your child. God bless you!',
    signature: '',
    preheader: "{{child_name}} has been picked up from Children's Church.",
    placeholders: {
      default_subject: 'Child pickup confirmation',
      checkout_time: '12:40',
      child_name: 'Tobi Obi',
      class_group: 'Toddlers',
      guardian_name: 'Mrs Obi',
      picked_up_by: 'Mrs Obi',
    },
    toVars: pick({
      checkout_time: 'checkoutTime',
      child_name: 'childName',
      class_group: 'classGroup',
      guardian_name: 'guardianName',
      picked_up_by: 'pickedUpBy',
    }),
    sampleData: {
      checkoutTime: '12:40',
      childName: 'Tobi Obi',
      classGroup: 'Toddlers',
      guardianName: 'Mrs Obi',
      pickedUpBy: 'Mrs Obi',
    },
  },
  'membership-anniversary': {
    category: EmailCategory.MEMBERSHIP_ANNIVERSARY,
    label: 'Membership anniversary',
    description: 'Sent on the anniversary of the day a member joined.',
    lockedNote: 'Nothing is locked — the whole message is yours.',
    subject: '{{default_subject}}',
    heading: 'Celebrating {{years}} Years, {{first_name}}!',
    message:
      "<p>On behalf of the entire {{church_name}} family, we're celebrating {{years}} years of your journey with us, {{full_name}}. Thank you for growing, serving, and worshipping with this congregation.</p>",
    closing:
      "<p>We're grateful for every season you've shared with us and look forward to many more.</p>",
    signoff: 'With love and prayers,',
    signature: '{{church_name}} Family',
    preheader:
      'Celebrating {{years}} years with {{church_name}}, {{first_name}}!',
    placeholders: {
      default_subject: 'Membership anniversary',
      full_name: 'Ada Obi',
      first_name: 'Ada',
      years: '5',
    },
    toVars: pick({
      full_name: 'full_name',
      first_name: 'name',
      years: 'years',
    }),
    sampleData: { full_name: 'Ada Obi', name: 'Ada', years: '5' },
  },
  'pledge-reminder': {
    category: EmailCategory.FINANCE_ALERTS,
    label: 'Pledge payment reminder',
    description: 'Sent when a pledge payment is coming up or overdue.',
    lockedNote:
      'The pledge banner, pledge details and portal button are always included.',
    subject: '{{default_subject}}',
    heading: 'Pledge Payment Reminder',
    message:
      '<p>This is a friendly reminder about your pledge commitment. Your faithful giving makes a real difference.</p>',
    closing: '',
    signoff: '',
    signature: '',
    preheader: 'Pledge reminder: {{campaign_name}} payment is {{status}}.',
    placeholders: {
      default_subject: 'Pledge payment reminder',
      campaign_name: 'Building Fund',
      due_date: '2026-10-05',
      frequency: 'Monthly',
      first_name: 'Ada',
      status: 'due in 3 days',
      total_amount: 'NGN 200,000',
    },
    toVars: pick({
      campaign_name: 'campaignName',
      due_date: 'dueDate',
      frequency: 'frequency',
      first_name: 'name',
      status: 'status',
      total_amount: 'totalAmount',
    }),
    sampleData: {
      campaignName: 'Building Fund',
      dueDate: '2026-10-05',
      frequency: 'Monthly',
      name: 'Ada',
      status: 'due in 3 days',
      totalAmount: 'NGN 200,000',
    },
  },
};
